import { useEffect,useRef,useState } from 'react';
import { lines,teams,bracket,shuffle,dateDifference,UNITS,convert,exportText,downloadBlob } from '../lib/studio';
import { Field,Output,useStudio } from './StudioShared';
export default function StudioTogether({id}){
 const[v,set]=useStudio(id,{text:'Nova\nCosmo\nLuna\nOrion',count:2,groups:[],rounds:[],winners:{},ranked:[],question:'What should we play next?',options:'Hush Moto\nRNG Roll\nA new game',a:'',b:'',category:'speed',from:'km/h',to:'mph',value:60,rate:1,voice:'',bpm:100,volume:.25,beats:Array.from({length:3},(_,r)=>Array.from({length:16},(_,i)=>r===0?i%4===0:r===1?i%8===4:i%2===0))}),[notice,message]=useState(''),[running,run]=useState(false),[step,stepSet]=useState(-1),[voices,voicesSet]=useState([]);
 const canvas=useRef(null),context=useRef(null),timer=useRef(null),next=useRef(0),counter=useRef(0),latest=useRef(v),utterance=useRef(null);latest.current=v;const patch=(k,x)=>set(old=>({...old,[k]:x}));
 useEffect(()=>{if(id!==47||!window.speechSynthesis)return;const change=()=>voicesSet(speechSynthesis.getVoices());change();speechSynthesis.addEventListener('voiceschanged',change);return()=>{speechSynthesis.removeEventListener('voiceschanged',change);if(utterance.current)speechSynthesis.cancel();};},[id]);
 useEffect(()=>()=>{clearInterval(timer.current);context.current?.close();},[]);
 useEffect(()=>{if(id!==44||!canvas.current)return;const c=canvas.current,x=c.getContext('2d'),g=x.createLinearGradient(0,0,1080,1080);g.addColorStop(0,'#201b43');g.addColorStop(1,'#0f353a');x.fillStyle=g;x.fillRect(0,0,1080,1080);x.fillStyle='#92f5d2';x.font='700 24px system-ui';x.fillText('ASTRAL / CREW VOTE',70,90);x.fillStyle='#fff';x.font='bold 48px system-ui';const words=v.question.split(' ');let row='',y=190;for(const w of words){if(x.measureText(row+w).width>900){x.fillText(row,70,y);row=w+' ';y+=60;}else row+=w+' ';}x.fillText(row,70,y);x.font='30px system-ui';lines(v.options).slice(0,6).forEach((o,i)=>{x.fillStyle='#ffffff16';x.fillRect(70,360+i*98,940,78);x.fillStyle='#fff';x.fillText(`${i+1}. ${o}`,98,411+i*98,870);});x.fillStyle='#b6c8d2';x.font='22px system-ui';x.fillText('Vote with your crew on Astral',70,1030);},[id,v.question,v.options]);
 const audio=async()=>{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){message('Web Audio is unavailable in this browser.');return null;}context.current||=new Audio();await context.current.resume();return context.current;};
 const tone=(ctx,hz,t,kind='sine',volume=.25)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=kind;osc.frequency.setValueAtTime(hz,t);if(hz<180)osc.frequency.exponentialRampToValueAtTime(40,t+.13);gain.gain.setValueAtTime(Math.max(.0001,volume*.3),t);gain.gain.exponentialRampToValueAtTime(.0001,t+.16);osc.connect(gain);gain.connect(ctx.destination);osc.start(t);osc.stop(t+.18);osc.onended=()=>{osc.disconnect();gain.disconnect();};};
 const toggle=async()=>{if(running){clearInterval(timer.current);run(false);stepSet(-1);return;}try{const ctx=await audio();if(!ctx)return;next.current=ctx.currentTime+.03;counter.current=0;run(true);const schedule=()=>{while(next.current<ctx.currentTime+.1){const o=latest.current,i=counter.current%(id===49?16:4);stepSet(i);if(id===49)o.beats.forEach((row,r)=>{if(row[i])tone(ctx,[110,280,1800][r],next.current,r===2?'square':'sine',o.volume);});else tone(ctx,i===0?1200:800,next.current,'sine',o.volume);next.current+=60/o.bpm/(id===49?4:1);counter.current++;}};schedule();timer.current=setInterval(schedule,25);}catch{message('Could not start audio. Try enabling sound for this page.');run(false);}};
 const participants=<Field label="Names · one per line"><textarea maxLength={5000} rows={7} value={v.text} onChange={e=>patch('text',e.target.value)}/></Field>;
 let content;
 if(id===41)content=<>{participants}<Field label="Number of teams"><input type="number" min="1" max="16" value={v.count} onChange={e=>patch('count',Math.max(1,Math.min(16,+e.target.value)))}/></Field><button className="btn btn-primary" disabled={!lines(v.text).length} onClick={()=>patch('groups',teams(lines(v.text),v.count))}>Shuffle teams</button><div className="studio-columns">{v.groups.map((g,i)=><section className="card" key={i}><h3>Team {i+1}</h3>{g.map((n,j)=><p key={j}>{n}</p>)}</section>)}</div><button className="btn" onClick={()=>exportText(v.groups.map((g,i)=>`Team ${i+1}: ${g.join(', ')}`).join('\n'),'astral-teams.txt')}>Export teams</button></>;
 if(id===42)content=<>{participants}<button className="btn btn-primary" disabled={lines(v.text).length<2} onClick={()=>set(old=>({...old,rounds:bracket(shuffle(lines(v.text).slice(0,16))),winners:{}}))}>Create bracket · up to 16 players</button><p className="muted">Choose each match winner. A solo entrant advances with one click. Changing a winner clears later rounds.</p><div className="studio-bracket">{v.rounds.map((round,r)=><section key={r}><h3>Round {r+1}</h3>{round.map((initial,m)=>{const pair=r===0?initial:[v.winners[`${r-1}.${m*2}`],v.winners[`${r-1}.${m*2+1}`]];return <div className="studio-match" key={m}>{pair.map((p,s)=><button key={s} className={'btn '+(v.winners[`${r}.${m}`]===p&&p?'btn-primary':'')} disabled={!p} onClick={()=>patch('winners',{...Object.fromEntries(Object.entries(v.winners).filter(([k])=>+k.split('.')[0]<=r)),[`${r}.${m}`]:p})}>{p||(r===0?'Bye':'Awaiting winner')}</button>)}</div>;})}</section>)}</div>{v.winners[`${v.rounds.length-1}.0`]&&<div className="studio-result">Champion: {v.winners[`${v.rounds.length-1}.0`]}</div>}</>;
 if(id===43)content=<>{participants}<button className="btn" onClick={()=>patch('ranked',lines(v.text).map(text=>({text,tier:'Unranked'})))}>Create tier list</button>{['S','A','B','C','Unranked'].map(tier=><section className="studio-tier" key={tier}><h3>{tier}</h3>{v.ranked.map((item,i)=>item.tier===tier&&<label key={i}>{item.text}<select aria-label={'Tier for '+item.text} value={tier} onChange={e=>patch('ranked',v.ranked.map((a,j)=>i===j?{...a,tier:e.target.value}:a))}>{['S','A','B','C','Unranked'].map(t=><option key={t}>{t}</option>)}</select></label>)}</section>)}<button className="btn" onClick={()=>exportText(v.ranked.map(i=>i.tier+': '+i.text).join('\n'),'astral-tiers.txt')}>Export ranking</button></>;
 if(id===44)content=<div className="studio-editor"><aside className="studio-controls"><Field label="Poll question"><input maxLength={90} value={v.question} onChange={e=>patch('question',e.target.value)}/></Field><Field label="Options · one per line, up to six"><textarea maxLength={500} rows={7} value={v.options} onChange={e=>patch('options',e.target.value)}/></Field><button className="btn btn-primary" onClick={()=>canvas.current.toBlob(b=>b&&downloadBlob(b,'astral-poll.png'))}>Download poll card</button><p className="muted">This creates an image. To collect votes, create a poll on Astral.</p><a className="btn" href="/polls">Open Astral polls</a></aside><div className="studio-preview"><canvas ref={canvas} width="1080" height="1080" aria-label="Poll card preview"/></div></div>;
 if(id===45)content=<><div className="studio-columns">{[['a','From date'],['b','To date']].map(([k,label])=><Field key={k} label={label}><input type="date" value={v[k]} onChange={e=>patch(k,e.target.value)}/></Field>)}</div><div className="studio-result">{dateDifference(v.a,v.b)===null?'Choose two dates':`${dateDifference(v.a,v.b)} days · ${(dateDifference(v.a,v.b)/7).toFixed(1)} weeks`}</div></>;
 if(id===46)content=<><Field label="Measurement"><select value={v.category} onChange={e=>{const c=e.target.value;set(old=>({...old,category:c,from:Object.keys(UNITS[c])[0],to:Object.keys(UNITS[c])[1]}));}}>{Object.keys(UNITS).map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Value"><input type="number" value={v.value} onChange={e=>patch('value',e.target.value)}/></Field><div className="studio-columns">{['from','to'].map(k=><Field key={k} label={k}><select value={v[k]} onChange={e=>patch(k,e.target.value)}>{Object.keys(UNITS[v.category]).map(u=><option key={u}>{u}</option>)}</select></Field>)}</div><div className="studio-result">{convert(v.value,v.category,v.from,v.to).toLocaleString(undefined,{maximumFractionDigits:6})} {v.to}</div></>;
 if(id===47)content=<><Field label="Text to read"><textarea rows={9} maxLength={10000} value={v.text} onChange={e=>patch('text',e.target.value)}/></Field><Field label="Browser voice"><select value={v.voice} onChange={e=>patch('voice',e.target.value)}><option value="">Default voice</option>{voices.map((voice,i)=><option key={i} value={voice.voiceURI}>{voice.name} · {voice.lang}</option>)}</select></Field><Field label={'Speech rate · '+v.rate}><input type="range" min="0.5" max="2" step="0.1" value={v.rate} onChange={e=>patch('rate',+e.target.value)}/></Field><div className="wrap"><button className="btn btn-primary" disabled={!v.text.trim()} onClick={()=>{if(!window.speechSynthesis)return message('Speech is unavailable in this browser.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(v.text);u.rate=v.rate;u.voice=voices.find(a=>a.voiceURI===v.voice)||null;u.onend=()=>message('Finished reading');u.onerror=()=>message('Could not play this voice. Try another.');utterance.current=u;speechSynthesis.speak(u);message('Reading aloud');}}>Read aloud</button><button className="btn" onClick={()=>window.speechSynthesis?.pause()}>Pause</button><button className="btn" onClick={()=>window.speechSynthesis?.resume()}>Resume</button><button className="btn" onClick={()=>{window.speechSynthesis?.cancel();message('Stopped');}}>Stop</button></div></>;
 if(id>=48)content=<><Field label={'Volume · '+Math.round(v.volume*100)+'%'}><input type="range" min="0" max="1" step="0.05" value={v.volume} onChange={e=>patch('volume',+e.target.value)}/></Field>{id===48?<div className="studio-soundboard">{[['C',261.63],['D',293.66],['E',329.63],['F',349.23],['G',392],['A',440],['B',493.88],['C↑',523.25]].map(([name,hz])=><button className="btn" key={name} onClick={async()=>{try{const ctx=await audio();if(ctx)tone(ctx,hz,ctx.currentTime,'triangle',v.volume);}catch{message('Audio is unavailable.');}}}>{name}</button>)}</div>:<><Field label={'Tempo · '+v.bpm+' BPM'}><input type="range" min="40" max="220" value={v.bpm} onChange={e=>patch('bpm',+e.target.value)}/></Field>{id===49?<div className="studio-sequencer">{v.beats.map((row,r)=><div key={r}><strong>{['Kick','Snare','Hat'][r]}</strong>{row.map((on,i)=><button key={i} aria-label={['Kick','Snare','Hat'][r]+' step '+(i+1)} aria-pressed={on} className={(on?'on ':'')+(step===i?'playing':'')} onClick={()=>patch('beats',v.beats.map((a,j)=>j===r?a.map((b,k)=>k===i?!b:b):a))}/>)}</div>)}</div>:<div className="studio-metronome">{[0,1,2,3].map(i=><span key={i} className={step===i?'on':''}>{i+1}</span>)}</div>}<button className="btn btn-primary" onClick={toggle}>{running?'Stop':'Play'}</button></>}</>;
 return <div className="studio-stack">{content}<p role="status">{notice}</p></div>;
}
