import { useEffect,useRef,useState } from 'react';
import { contrast,escapeXML,downloadBlob,exportText } from '../lib/studio';
import { Field,useStudio } from './StudioShared';
const randomColor=()=>'#'+Math.floor(Math.random()*0xffffff).toString(16).padStart(6,'0');
export default function StudioDesign({id}){
 const[v,set]=useStudio(id,{a:'#8872ff',b:'#4ee1b4',angle:135,x:10,y:20,blur:40,spread:0,radius:24,border:3,title:'MAKE SOMETHING GREAT',subtitle:'ASTRAL ORIGINAL',seed:'ASTRAL',size:36,palette:['#8872ff','#4ee1b4','#ffc477','#e980bd','#17243b'],pixels:{},paths:[]}),[notice,message]=useState('');const patch=(k,x)=>set(old=>({...old,[k]:x}));
 const canvas=useRef(null),drawing=useRef(false),last=useRef(null),path=useRef([]),[history,historySet]=useState([]);
 const css=id===31?`background: linear-gradient(${v.angle}deg, ${v.a}, ${v.b});`:id===34?`box-shadow: ${v.x}px ${v.y}px ${v.blur}px ${v.spread}px ${v.a};`:`border: ${v.border}px solid ${v.a};\nborder-radius: ${v.radius}px;`;
 const color=(key,label)=><Field label={label}><input type="color" value={v[key]} onChange={e=>patch(key,e.target.value)}/></Field>;
 const range=(key,label,min,max)=><Field label={`${label} · ${v[key]}`}><input type="range" value={v[key]} min={min} max={max} onChange={e=>patch(key,+e.target.value)}/></Field>;
 let shapes='';if(id===36){let hash=[...v.seed].reduce((n,c)=>Math.imul(n,31)+c.charCodeAt(0),17)>>>0;for(let y=0;y<5;y++)for(let x=0;x<3;x++){hash=(Math.imul(hash,1664525)+1013904223)>>>0;if(hash%3){for(const px of new Set([x,4-x]))shapes+=`<rect x="${px*80+40}" y="${y*80+40}" width="80" height="80" rx="12" fill="${v.a}"/>`;}}}
 const svg=id===36?`<svg xmlns="http://www.w3.org/2000/svg" width="480" height="480"><rect width="480" height="480" rx="70" fill="${v.b}"/>${shapes}</svg>`:id===37?`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="400"><defs><linearGradient id="g"><stop stop-color="${v.a}"/><stop offset="1" stop-color="${v.b}"/></linearGradient></defs><rect width="1200" height="400" fill="url(#g)"/><circle cx="1120" cy="10" r="280" fill="white" opacity=".15"/><text x="70" y="190" fill="#fff" font-family="sans-serif" font-size="54" font-weight="bold">${escapeXML(v.title.slice(0,32))}</text><text x="74" y="250" fill="#fff" font-family="sans-serif" font-size="24">${escapeXML(v.subtitle.slice(0,65))}</text></svg>`:`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="800"><defs><pattern id="p" width="${v.size}" height="${v.size}" patternUnits="userSpaceOnUse"><circle cx="${v.size/2}" cy="${v.size/2}" r="${v.size/5}" fill="${v.a}"/></pattern></defs><rect width="800" height="800" fill="${v.b}"/><rect width="800" height="800" fill="url(#p)"/></svg>`;
 const redraw=()=>{const c=canvas.current;if(!c)return;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,640,640);if(id===38){Object.entries(v.pixels).forEach(([key,color])=>{const[n,m]=key.split(',').map(Number);x.fillStyle=color;x.fillRect(n*20,m*20,20,20);});x.strokeStyle='#80808022';for(let n=0;n<=32;n++){x.beginPath();x.moveTo(n*20,0);x.lineTo(n*20,640);x.moveTo(0,n*20);x.lineTo(640,n*20);x.stroke();}}else for(const p of v.paths){x.strokeStyle=p.color;x.lineWidth=p.size;x.lineCap=x.lineJoin='round';x.beginPath();p.points.forEach(([a,b],i)=>i?x.lineTo(a,b):x.moveTo(a,b));x.stroke();}};
 useEffect(redraw,[id,v.pixels,v.paths]);
 const point=e=>{const rect=canvas.current.getBoundingClientRect();return[(e.clientX-rect.left)/rect.width*640,(e.clientY-rect.top)/rect.height*640];};
 const move=e=>{if(!drawing.current)return;const p=point(e);if(id===38){const key=Math.max(0,Math.min(31,Math.floor(p[0]/20)))+','+Math.max(0,Math.min(31,Math.floor(p[1]/20)));set(old=>({...old,pixels:{...old.pixels,[key]:v.a}}));}else{const x=canvas.current.getContext('2d');x.strokeStyle=v.a;x.lineWidth=v.border*2;x.lineCap='round';x.beginPath();x.moveTo(...last.current);x.lineTo(...p);x.stroke();path.current.push(p);last.current=p;}};
 const finish=()=>{if(!drawing.current)return;drawing.current=false;if(id===39&&path.current.length){patch('paths',[...v.paths,{color:v.a,size:v.border*2,points:path.current}].slice(-200));path.current=[];}};
 const ratio=id===32?contrast(v.a,v.b):0;
 return <div className="studio-editor"><aside className="studio-controls">{color('a',id===32?'Text color':'Primary color')}{![34,35,38,39].includes(id)&&color('b',id===32?'Background color':'Secondary color')}
 {id===31&&range('angle','Gradient angle',0,360)}{id===34&&<>{range('x','Horizontal offset',-50,50)}{range('y','Vertical offset',-50,50)}{range('blur','Blur',0,100)}{range('spread','Spread',-20,30)}</>}{id===35&&<>{range('radius','Corner radius',0,100)}{range('border','Border width',0,20)}</>}
 {id===36&&<Field label="Avatar seed"><input value={v.seed} maxLength={80} onChange={e=>patch('seed',e.target.value)}/></Field>}
 {id===37&&<>{['title','subtitle'].map(k=><Field key={k} label={k}><input maxLength={k==='title'?32:65} value={v[k]} onChange={e=>patch(k,e.target.value)}/></Field>)}</>}
 {id===40&&range('size','Pattern spacing',12,100)}
 {id===33&&<button className="btn btn-primary" onClick={()=>patch('palette',Array.from({length:5},randomColor))}>Generate palette</button>}
 {(id===38||id===39)&&<>{id===39&&range('border','Brush size',1,20)}<button className="btn" disabled={!history.length} onClick={()=>{set(history[history.length-1]);historySet(h=>h.slice(0,-1));}}>Undo stroke</button><button className="btn" onClick={()=>{historySet(h=>[...h.slice(-9),v]);patch(id===38?'pixels':'paths',id===38?{}:[]);}}>Clear canvas</button><button className="btn btn-primary" onClick={()=>canvas.current.toBlob(blob=>blob&&downloadBlob(blob,'astral-art.png'))}>Download PNG</button></>}
 {[36,37,40].includes(id)&&<button className="btn btn-primary" onClick={()=>downloadBlob(new Blob([svg],{type:'image/svg+xml'}),'astral-design.svg')}>Download SVG</button>}
 {[31,34,35].includes(id)&&<button className="btn btn-primary" onClick={()=>exportText(css,'astral-style.css')}>Download CSS</button>}<span role="status">{notice}</span></aside>
 <div className="studio-preview">{id===31&&<div className="studio-design-sample" style={{background:`linear-gradient(${v.angle}deg,${v.a},${v.b})`}}/>}{id===32&&<><div className="studio-design-sample" style={{background:v.b,color:v.a}}><h2>Read me clearly.</h2><p>The quick brown fox jumps over the lazy dog.</p></div><div className="studio-result">{ratio.toFixed(2)}:1 contrast · {ratio>=4.5?'Meets 4.5:1 text target':'Below 4.5:1 text target'}</div></>}
 {id===33&&<div className="studio-swatches">{v.palette.map((c,i)=><button key={i} style={{borderTop:`120px solid ${c}`}} onClick={()=>navigator.clipboard.writeText(c).then(()=>message('Copied '+c)).catch(()=>message(c))}>{c}</button>)}</div>}
 {(id===34||id===35)&&<div className="studio-sample-area"><div style={id===34?{boxShadow:`${v.x}px ${v.y}px ${v.blur}px ${v.spread}px ${v.a}`}:{border:`${v.border}px solid ${v.a}`,borderRadius:v.radius}}>Astral</div></div>}
 {[31,34,35].includes(id)&&<pre>{css}</pre>}{[36,37,40].includes(id)&&<img alt="Generated design preview" src={'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)}/>}
 {(id===38||id===39)&&<canvas width="640" height="640" ref={canvas} aria-label={id===38?'32 by 32 pixel art canvas':'Drawing canvas'} style={{touchAction:'none',cursor:'crosshair'}} onPointerDown={e=>{historySet(h=>[...h.slice(-9),v]);e.currentTarget.setPointerCapture(e.pointerId);drawing.current=true;last.current=point(e);path.current=[last.current];move(e);}} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish}/>}</div></div>;
}
