import { useEffect,useRef,useState } from 'react';
import { lines,exportText } from '../lib/studio';
import { Field,useStudio } from './StudioShared';
const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const today=()=>new Date().toLocaleDateString('en-CA');
const time=n=>`${Math.floor(Math.max(0,n)/60).toString().padStart(2,'0')}:${Math.floor(Math.max(0,n)%60).toString().padStart(2,'0')}`;
export default function StudioPlanning({id}){
 const [v,set]=useStudio(id,{items:[],text:'Pizza\nMovie night\nHush Moto',minutes:25,running:false,started:0,elapsed:0,deadline:0,week:{},date:'',title:'The next big thing',note:'',habits:{}}),[input,edit]=useState(''),[now,tick]=useState(Date.now()),[selected,select]=useState(''),[spinning,spin]=useState(false),[angle,rotate]=useState(0),[trash,undo]=useState(null);const spinTimer=useRef();
 const patch=(k,x)=>set(old=>({...old,[k]:x}));useEffect(()=>{const t=setInterval(()=>tick(Date.now()),200);return()=>{clearInterval(t);clearTimeout(spinTimer.current);};},[]);
 useEffect(()=>{if(id===24&&v.running&&now>=v.deadline){set(old=>({...old,running:false,elapsed:0,complete:true}));select('Focus complete. Take a break.');}},[id,now,v.running,v.deadline]);
 const add=()=>{if(!input.trim())return;set(old=>({...old,items:[...old.items,{id:crypto.randomUUID(),text:input.trim(),done:false,status:'To do',star:false}]}));edit('');};
 const update=(item,change)=>patch('items',v.items.map(i=>i.id===item.id?{...i,...change}:i));const remove=item=>{undo(item);patch('items',v.items.filter(i=>i.id!==item.id));};
 const listInput=<form className="studio-inline" onSubmit={e=>{e.preventDefault();add();}}><input aria-label="New item" maxLength={300} value={input} placeholder={id===27?'New habit…':'Add an item…'} onChange={e=>edit(e.target.value)}/><button className="btn btn-primary">Add</button></form>;
 const itemRow=item=><div className="studio-task" key={item.id}>{id===22&&<input aria-label={'Complete '+item.text} type="checkbox" checked={item.done} onChange={e=>update(item,{done:e.target.checked})}/>}<span style={{textDecoration:item.done?'line-through':'none'}}>{item.text}</span>{id===29&&<button className="btn btn-sm" aria-label={'Prioritize '+item.text} aria-pressed={item.star} onClick={()=>update(item,{star:!item.star})}>{item.star?'★':'☆'}</button>}{id===23&&<select aria-label={'Status of '+item.text} value={item.status} onChange={e=>update(item,{status:e.target.value})}>{['To do','Doing','Done'].map(s=><option key={s}>{s}</option>)}</select>}<button className="btn btn-sm" aria-label={'Remove '+item.text} onClick={()=>remove(item)}>×</button></div>;
 let content;
 if(id===21)content=<><Field label="Note title"><input value={v.title} onChange={e=>patch('title',e.target.value)}/></Field><Field label="Private note"><textarea rows={14} maxLength={50000} value={v.note} onChange={e=>patch('note',e.target.value)} placeholder="A thought worth keeping…"/></Field><button className="btn" onClick={()=>exportText(v.title+'\n\n'+v.note,'astral-note.txt')}>Export note</button></>;
 if([22,23,29].includes(id))content=<>{listInput}{id===23?<div className="studio-kanban">{['To do','Doing','Done'].map(s=><section key={s}><h3>{s}</h3>{v.items.filter(i=>i.status===s).map(itemRow)}</section>)}</div>:<div>{[...v.items].sort((a,b)=>Number(b.star)-Number(a.star)).map(itemRow)}{!v.items.length&&<p className="studio-empty">Add your first {id===29?'idea':'task'}.</p>}</div>}{id===22&&<p>{v.items.filter(i=>i.done).length} of {v.items.length} complete</p>}{trash&&<button className="btn" onClick={()=>{patch('items',[...v.items,trash]);undo(null);}}>Undo removal</button>}<button className="btn" onClick={()=>exportText(v.items.map(i=>`${i.done?'✓':'○'} ${i.text}${id===23?' — '+i.status:''}`).join('\n'),'astral-list.txt')}>Export list</button></>;
 if(id===24||id===25){const elapsed=v.elapsed+(v.running?(now-v.started)/1000:0),remaining=v.complete?0:v.running?(v.deadline-now)/1000:v.elapsed||v.minutes*60;content=<>{id===24&&<Field label="Focus minutes"><input type="number" min="1" max="180" disabled={v.running} value={v.minutes} onChange={e=>set(old=>({...old,minutes:Math.max(1,Math.min(180,+e.target.value)),elapsed:0,complete:false}))}/></Field>}<div className="studio-timer" role="timer">{time(id===24?remaining:elapsed)}</div><div className="wrap"><button className="btn btn-primary" onClick={()=>{const n=Date.now();tick(n);set(old=>({...old,running:!old.running,complete:false,started:n,deadline:n+(old.elapsed||old.minutes*60)*1000,elapsed:old.running?(id===24?Math.max(0,(old.deadline-n)/1000):old.elapsed+(n-old.started)/1000):old.elapsed}));select('');}}>{v.running?'Pause':'Start'}</button><button className="btn" onClick={()=>set(old=>({...old,running:false,complete:false,items:id===25?[]:old.items,elapsed:0,started:0,deadline:0}))}>Reset</button>{id===25&&<button className="btn" onClick={()=>patch('items',[...v.items,{id:crypto.randomUUID(),text:time(elapsed)}])}>Lap</button>}</div>{id===25&&v.items.map((lap,i)=><p key={lap.id}>Lap {i+1} · {lap.text}</p>)}<p role="status">{selected}</p></>;}
 if(id===26)content=<><Field label="Event name"><input value={v.title} onChange={e=>patch('title',e.target.value)}/></Field><Field label="Local date and time"><input type="datetime-local" value={v.date} onChange={e=>patch('date',e.target.value)}/></Field><div className="studio-result">{v.date?(new Date(v.date).getTime()<=now?'It’s time for '+v.title:Math.floor((new Date(v.date)-now)/86400000)+' days · '+time(((new Date(v.date)-now)/1000)%86400)+' until '+v.title):'Choose a date to start your countdown.'}</div></>;
 if(id===27){const dates=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return d.toLocaleDateString('en-CA');});content=<>{listInput}<div className="studio-habits">{v.items.map(item=><section key={item.id}><h3>{item.text}</h3><div className="wrap">{dates.map(date=><label key={date}><span>{date.slice(-5)}</span><input type="checkbox" aria-label={item.text+' '+date} checked={!!v.habits[item.id+'-'+date]} onChange={e=>patch('habits',{...v.habits,[item.id+'-'+date]:e.target.checked})}/></label>)}<button className="btn btn-sm" onClick={()=>remove(item)}>Remove</button></div></section>)}</div></>;}
 if(id===28)content=<div className="studio-week">{days.map(day=><Field label={day} key={day}><textarea rows={4} maxLength={3000} placeholder="Plans…" value={v.week[day]||''} onChange={e=>patch('week',{...v.week,[day]:e.target.value})}/></Field>)}</div>;
 if(id===30)content=<><Field label="Choices · one per line"><textarea rows={6} value={v.text} maxLength={5000} onChange={e=>patch('text',e.target.value)}/></Field><div className="studio-wheel" style={{transform:`rotate(${angle}deg)`}}>✦</div><button className="btn btn-primary" disabled={spinning||!lines(v.text).length} onClick={()=>{const options=lines(v.text);spin(true);rotate(a=>a+1080+Math.random()*360);select('');spinTimer.current=setTimeout(()=>{select(options[Math.floor(Math.random()*options.length)]);spin(false);},1400);}}>Spin a choice</button><div className="studio-result" role="status">{selected||'Your next adventure?'}</div></>;
 return <div className="studio-stack">{content}<small className="muted">Saved on this device for your account. Timers use the clock, even when this tab is in the background.</small></div>;
}
