import { useState } from 'react';
import { textTool,exportText } from '../lib/studio';
import { Field,Output,useStudio } from './StudioShared';

export default function StudioWriting({id}){
 const [v,set]=useStudio(id,{text:'',other:'',mode:'upper',find:'',replace:'',topic:'riding with the crew',tone:'funny'}),[notice,message]=useState(''),[captions,setCaptions]=useState('');const patch=(k,x)=>set(old=>({...old,[k]:x}));
 const left=v.text.split('\n'),right=v.other.split('\n');
 const output=textTool(id,v.text,v),copy=async()=>{try{await navigator.clipboard.writeText(id===20?captions:output);message('Copied');}catch{message('Select the result and copy it.');}};
 const generate=()=>{const topic=v.topic.trim()||'the weekend';const decks={funny:[`POV: ${topic} was supposed to take five minutes.`,`Nobody: / Me: ${topic}.`,`My last two brain cells planning ${topic}.`,`Current status: emotionally invested in ${topic}.`,`Tell me you love ${topic} without telling me.`],dramatic:[`One night. One crew. ${topic}.`,`They said it could not happen. Then came ${topic}.`,`This is where ${topic} begins.`,`Some moments change everything. ${topic}.`],kind:[`A little more ${topic}, a little less worry.`,`Good people. Good memories. ${topic}.`,`Making time for ${topic}.`,`Your reminder to enjoy ${topic}.`]};setCaptions(decks[v.tone].sort(()=>Math.random()-.5).join('\n\n'));};
 return <div className="studio-stack">{id===20?<><Field label="Topic"><input maxLength={100} value={v.topic} onChange={e=>patch('topic',e.target.value)}/></Field><Field label="Mood"><select value={v.tone} onChange={e=>patch('tone',e.target.value)}><option value="funny">Funny</option><option value="dramatic">Dramatic</option><option value="kind">Feel-good</option></select></Field><button className="btn btn-primary" onClick={generate}>Shuffle caption prompts</button><Output value={captions}/><p className="muted">A handmade prompt deck to help you write your own captions.</p></>:<><Field label="Your text"><textarea maxLength={50000} rows={8} value={v.text} placeholder="Type or paste text…" onChange={e=>patch('text',e.target.value)}/></Field>
 {id===12&&<Field label="Letter case"><select value={v.mode} onChange={e=>patch('mode',e.target.value)}><option value="upper">UPPERCASE</option><option value="lower">lowercase</option><option value="title">Title Case</option></select></Field>}
 {id===13&&<div className="studio-columns"><Field label="Find (literal text)"><input value={v.find} onChange={e=>patch('find',e.target.value)}/></Field><Field label="Replace with"><input value={v.replace} onChange={e=>patch('replace',e.target.value)}/></Field></div>}
 {id===15&&<Field label="Sort order"><select value={v.mode} onChange={e=>patch('mode',e.target.value)}><option value="upper">A–Z</option><option value="reverse">Z–A</option></select></Field>}
 {id===16?<><Field label="Compare with"><textarea rows={8} maxLength={50000} value={v.other} onChange={e=>patch('other',e.target.value)}/></Field><div className="studio-diff">{Array.from({length:Math.min(2000,Math.max(left.length,right.length))},(_,i)=>{const a=left[i],b=right[i];return a===b?<div key={i}>{a||' '}</div>:<div key={i}>{a!==undefined&&<del>− {a}</del>}{b!==undefined&&<ins>+ {b}</ins>}</div>;})}</div><p className="muted">Comparison aligns text by line number and shows up to 2,000 lines.</p></>:id===17?<div className="studio-markdown">{v.text.split('\n').map((line,i)=>line.startsWith('# ')?<h1 key={i}>{line.slice(2)}</h1>:line.startsWith('## ')?<h2 key={i}>{line.slice(3)}</h2>:line.startsWith('- ')?<p key={i}>• {line.slice(2)}</p>:<p key={i}>{line.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).map((part,j)=>part.startsWith('**')?<strong key={j}>{part.slice(2,-2)}</strong>:part.startsWith('`')?<code key={j}>{part.slice(1,-1)}</code>:part)}</p>)}</div>:id===11?<div className="studio-result">{output}</div>:<Output value={output}/>}</>}
 <div className="wrap"><button className="btn" onClick={copy}>Copy {id===16||id===17?'source':'result'}</button><button className="btn" onClick={()=>exportText(id===20?captions:output,'astral-writing.txt')}>Download text</button><span role="status">{notice}</span></div></div>;
}
